name: Run Tests CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '14' ]

    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm install
      - name: Install Java 14
        uses: actions/setup-java@v1
        with:
          java-version: '14'
          java-package: jdk
          architecture: x64
      - name: Run tests against Firebase emulator
        run: |
          npm install -g firebase-tools
          firebase emulators:exec --only firestore --project integrify-emulator 'npm run test:ci'
      - uses: IgnusG/jest-report-action@v2.3.3
        if: always()
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          junit-file: 'junit.xml'
          run-name: 'Jest Test Report'